### ISSUE TITLE
OMOP -  observations?

### ISSUE THREAD

**Issue by rkboyce** [nyuvis/patient-viz#56]
Hi,

I am testing patient-viz against a OMOP CDM v5. Procedures and conditions look great but I don't see any observations. Wondered if this was available.

thanks,
-R

**Comment by JosuaKrause** [comment]
Yes, I never implemented it since I don't have a database at hand that populates those tables. What are the important fields? Or, if you want to implement the bit yourself you can look [here](https://github.com/nyuvis/patient-viz/blob/master/omop.py#L333-L380) and [here](https://github.com/nyuvis/patient-viz/blob/master/omop.py#L473) as example. Pull requests are always welcome :)
